exports.Description = {
    password : 'Enter password: ',
    repeatPassword : 'Reenter password: ',
    localAddress: 'Enter the index of the MAN address(1, 2, 3..):',
    solidity: 'Enter contract solidity file full path name:',
    funcName: 'Enter contract function name:',
    contractName: 'Enter contract name:',
    transactionHash: 'Enter the index of the transaction hash(1, 2, 3..):',
    localWANAddress: 'Enter the index of the WAN address(1, 2, 3..):',
    localETHAddress: 'Enter the index of the ETH address(1, 2, 3..):',
    getStoremanGroup: 'Enter the index of the StoremanGroup address(1, 2, 3..):',
    lockTxHash: 'Enter the index of the lockTransaction hash(1, 2, 3..):',
    toAddress: 'Enter Recipient\'s address:',
    address: 'Enter account address:',
    amount: 'Enter transfer amount(Up to 18 decimal places): ',
    inputFee: 'Input the transaction fee:',
    gasLimit: 'Input gas limit: ',
    gasPrice: 'Input gas price (Price limit is between 18Gwin-600Gwin): ',
    submitSend: 'Do you confirm to send transaction? [Y]es or [N]o : ',
    tokenBalance : 'Select an token balance by inputting No. (1, 2, 3..):',

}
exports.Message = {
    errPassword : 'Password invalid or too short!',
    errRepeatPass : 'Password invalid',
    errOptionNum : 'You entered the wrong number.',
    errAddress : 'The address entered is invalid.',
    errAmount : 'The amount entered is invalid.',
    errInput : 'Invalid input.',
    errSubmit : "you should input y(Y) or n(N) :",
    errFileName : "Invalid input File Name.",
    errcontractName: "Invalid input contract Name.",
    gasLimit: "Invalid Gas limit",
    gasPrice: "Price invalid!",
}